version: '3.8'

services:
  agent:
    build: .
    container_name: robot-agent
    devices:
      - /dev/gpiomem:/dev/gpiomem
      - /dev/video0:/dev/video0
      - /dev/media0:/dev/media0
      - /dev/dma_heap:/dev/dma_heap
    privileged: true
    cap_add:
      - SYS_RAWIO
    environment:
      XMPP_SERVER: "prosody"
      XMPP_PORT: 5222
      XMPP_DOMAIN: "isc-coordinator.lan"
      XMPP_USERNAME: "alberto-robot"
      XMPP_PASSWORD: "top_secret"
      PYTHONUNBUFFERED: 1
    volumes:
      - /run/udev:/run/udev:ro
      - ./agent:/agent
    ports:
      - 10000:10000
